import { NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase';

export async function POST() {
  const supabase = createServiceClient();
  const userId = 'demo-user';

  // Clear existing demo tasks first
  await supabase.from('tasks').delete().eq('user_id', userId);

  const now = new Date();
  const h = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();

  const tasks = [
    {
      user_id: userId,
      title: 'Submit Q3 investor report',
      description: 'Compile revenue metrics, churn analysis, and growth projections for board deck',
      category: 'work',
      priority: 'critical',
      status: 'in_progress',
      deadline: h(6),
      estimated_hours: 4,
      risk_score: 91,
      risk_level: 'critical',
      ai_recommendation: 'Only 6 hours left with 4h of work — start immediately or negotiate deadline',
      procrastination_count: 3,
      created_at: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'Fix critical auth bug in production',
      description: 'Users unable to reset passwords — affecting 12% of signups',
      category: 'work',
      priority: 'high',
      status: 'in_progress',
      deadline: h(10),
      estimated_hours: 3,
      risk_score: 74,
      risk_level: 'high',
      ai_recommendation: 'High impact bug — block 2 hours this afternoon to resolve before EOD',
      procrastination_count: 1,
      created_at: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'Prepare client presentation — TechCorp',
      description: 'Product demo + pricing proposal for enterprise deal worth $120k ARR',
      category: 'work',
      priority: 'high',
      status: 'pending',
      deadline: h(28),
      estimated_hours: 5,
      risk_score: 62,
      risk_level: 'high',
      ai_recommendation: 'Schedule 2h tonight + 3h tomorrow morning to hit this comfortably',
      procrastination_count: 2,
      created_at: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'Review and merge 4 open PRs',
      description: 'Backend team waiting on reviews blocking their sprint velocity',
      category: 'work',
      priority: 'medium',
      status: 'pending',
      deadline: h(48),
      estimated_hours: 2,
      risk_score: 38,
      risk_level: 'medium',
      ai_recommendation: 'Batch review all 4 in one 2h session — do it before lunch tomorrow',
      procrastination_count: 1,
      created_at: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'Write weekly team retrospective',
      description: 'What went well, blockers, action items for next sprint',
      category: 'work',
      priority: 'medium',
      status: 'pending',
      deadline: h(52),
      estimated_hours: 1,
      risk_score: 22,
      risk_level: 'low',
      ai_recommendation: 'Low risk — 30 min Friday morning is enough',
      procrastination_count: 0,
      created_at: new Date().toISOString(),
    },
    {
      user_id: userId,
      title: 'Renew gym membership + book PT session',
      description: 'Membership expired 3 days ago — also schedule first PT session',
      category: 'health',
      priority: 'medium',
      status: 'pending',
      deadline: h(72),
      estimated_hours: 1,
      risk_score: 45,
      risk_level: 'medium',
      ai_recommendation: 'Quick 10-min task — do it between meetings today',
      procrastination_count: 4,
      created_at: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'File advance tax payment',
      description: 'Q2 advance tax due — penalty kicks in after deadline',
      category: 'finance',
      priority: 'high',
      status: 'pending',
      deadline: h(20),
      estimated_hours: 2,
      risk_score: 78,
      risk_level: 'high',
      ai_recommendation: 'Financial penalty risk — block 2h tonight, do not delay further',
      procrastination_count: 2,
      created_at: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'Complete Next.js advanced course — Module 6',
      description: 'App Router deep dive — needed for upcoming project migration',
      category: 'learning',
      priority: 'low',
      status: 'pending',
      deadline: h(120),
      estimated_hours: 3,
      risk_score: 18,
      risk_level: 'low',
      ai_recommendation: 'On track — 2 sessions of 1.5h over the weekend is perfect',
      procrastination_count: 0,
      created_at: new Date().toISOString(),
    },
    {
      user_id: userId,
      title: 'Deploy v2.1.0 to production',
      description: 'Includes 3 feature flags, DB migration, and CDN cache purge',
      category: 'work',
      priority: 'high',
      status: 'completed',
      deadline: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
      estimated_hours: 2,
      risk_score: 0,
      risk_level: 'low',
      ai_recommendation: null,
      procrastination_count: 0,
      completed_at: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
      created_at: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      user_id: userId,
      title: 'Send follow-up to 3 leads from DevConf',
      description: 'Hot leads from conference — personalized email + LinkedIn connect',
      category: 'work',
      priority: 'medium',
      status: 'completed',
      deadline: new Date(now.getTime() - 5 * 60 * 60 * 1000).toISOString(),
      estimated_hours: 1,
      risk_score: 0,
      risk_level: 'low',
      ai_recommendation: null,
      procrastination_count: 0,
      completed_at: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
      created_at: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  const { error } = await supabase.from('tasks').insert(tasks);
  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  return NextResponse.json({ success: true, count: tasks.length });
}
