import { NextResponse } from 'next/server';

const now = new Date();
const h = (hours: number) => new Date(now.getTime() + hours * 3600000).toISOString();

export async function GET() {
  const demoTasks = [
    {
      id: 'demo-1',
      user_id: 'demo',
      title: 'Hackathon Final Submission',
      description: 'Submit the complete project with README, demo video, and deployed link',
      category: 'work',
      priority: 'critical',
      status: 'in_progress',
      deadline: h(6),
      estimated_hours: 4,
      actual_hours: 1.5,
      risk_score: 91,
      risk_level: 'critical',
      ai_recommendation: 'You have 6 hours but need 4 focused hours. Start the demo video NOW — it takes longer than expected.',
      procrastination_count: 2,
      is_recurring: false,
      created_at: h(-48),
      updated_at: now.toISOString(),
    },
    {
      id: 'demo-2',
      user_id: 'demo',
      title: 'Record Product Demo Video',
      description: '3-min walkthrough of all features for judges',
      category: 'work',
      priority: 'critical',
      status: 'pending',
      deadline: h(4),
      estimated_hours: 2,
      actual_hours: 0,
      risk_score: 84,
      risk_level: 'critical',
      ai_recommendation: 'Recording + editing typically takes 2-3x longer than expected. Block 2 hours now.',
      procrastination_count: 1,
      is_recurring: false,
      created_at: h(-24),
      updated_at: now.toISOString(),
    },
    {
      id: 'demo-3',
      user_id: 'demo',
      title: 'Client Proposal — Q3 Strategy',
      description: 'Prepare 15-slide strategy deck for enterprise client',
      category: 'work',
      priority: 'high',
      status: 'pending',
      deadline: h(18),
      estimated_hours: 5,
      actual_hours: 0,
      risk_score: 67,
      risk_level: 'high',
      ai_recommendation: 'With hackathon deadline today, delegate slides 8-15 or reschedule to tomorrow morning.',
      procrastination_count: 3,
      is_recurring: false,
      created_at: h(-72),
      updated_at: now.toISOString(),
    },
    {
      id: 'demo-4',
      user_id: 'demo',
      title: 'Deploy to Production',
      description: 'Deploy final app to Vercel with all env vars configured',
      category: 'work',
      priority: 'high',
      status: 'pending',
      deadline: h(5),
      estimated_hours: 1,
      actual_hours: 0,
      risk_score: 72,
      risk_level: 'high',
      ai_recommendation: 'Set up Vercel now — DNS propagation can delay this by 30 min.',
      procrastination_count: 0,
      is_recurring: false,
      created_at: h(-12),
      updated_at: now.toISOString(),
    },
    {
      id: 'demo-5',
      user_id: 'demo',
      title: 'Weekly Team Sync Prep',
      description: 'Prepare agenda and action items for Monday standup',
      category: 'work',
      priority: 'medium',
      status: 'pending',
      deadline: h(48),
      estimated_hours: 1,
      actual_hours: 0,
      risk_score: 22,
      risk_level: 'low',
      ai_recommendation: 'Low urgency — handle this after hackathon submission.',
      procrastination_count: 0,
      is_recurring: true,
      created_at: h(-24),
      updated_at: now.toISOString(),
    },
    {
      id: 'demo-6',
      user_id: 'demo',
      title: 'Workout — Leg Day',
      description: '45-min strength training',
      category: 'health',
      priority: 'medium',
      status: 'pending',
      deadline: h(20),
      estimated_hours: 1,
      actual_hours: 0,
      risk_score: 35,
      risk_level: 'medium',
      ai_recommendation: 'Schedule this for 8pm after hackathon submission — reward yourself.',
      procrastination_count: 1,
      is_recurring: true,
      created_at: h(-2),
      updated_at: now.toISOString(),
    },
  ];

  const demoBrief = {
    greeting: `Good ${new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 17 ? 'afternoon' : 'evening'}, Commander.`,
    mission_statement: 'Your hackathon window is closing — 3 critical tasks need immediate action before the 6-hour mark.',
    top_task: { id: 'demo-1', title: 'Hackathon Final Submission' },
    top_task_reason: '91% failure probability. You need 4 focused hours but only have 6 left. Every minute of delay increases your risk.',
    risk_alerts: [
      {
        task_id: 'demo-2',
        task_title: 'Record Product Demo Video',
        risk_level: 'critical',
        message: 'You have 4 hours but demo recording typically takes 2-3x longer. Start immediately after reading this.',
      },
      {
        task_id: 'demo-4',
        task_title: 'Deploy to Production',
        risk_level: 'high',
        message: 'Deployment + DNS propagation needs 30-60 min buffer. Do this before recording the demo.',
      },
    ],
    daily_schedule_summary: 'Next 6 hours: Deploy (1h) → Record demo (2h) → Final submission (1h) → Buffer (2h). Skip all non-critical tasks.',
    motivational_note: "You built something real. Now ship it. The difference between winners and almost-winners is finishing.",
  };

  return NextResponse.json({ tasks: demoTasks, brief: demoBrief, isDemo: true });
}
